fabdefensAdmin/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ask.Controllers
{
    public class AboutController : Controller
    {
        //
        // GET: /About/

        public ActionResult Index()
        {
            return View();
        }

    }
}

fabdefensAdmin/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ask.Controllers
{
    public class BlogController : Controller
    {
        //
        // GET: /Blog/

        public ActionResult Index()
        {
            return View();
        }

    }
}

fabdefensAdmin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ask.Controllers
{
    public class CategoryController : Controller
    {
        //
        // GET: /Countries/

        public ActionResult Index()
        {
          
            return View();
        }

    }


}

fabdefensAdmin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MySql.Data.MySqlClient;

namespace ask.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            MySqlConnection Connection = new MySqlConnection("Database=u9839606_fab;Data Source=37.140.192.117;User Id=u9839_root1;Password=archybaldo332");



            string categories = @"SELECT * FROM categories";

            string whepons = @"SELECT * FROM whepons";

            DataTable ct = new DataTable();

            DataTable wp = new DataTable();


            using (Connection){
                Connection.Open();
                MySqlCommand com = new MySqlCommand(categories, Connection);
                using (MySqlDataReader ds = com.ExecuteReader()){
                    if (ds.HasRows){
                        ct.Load(ds);
                    }
                }
            }
            using (Connection)
            {
                Connection.Open();
                MySqlCommand com = new MySqlCommand(whepons, Connection);
                using (MySqlDataReader ds = com.ExecuteReader())
                {
                    if (ds.HasRows)
                    {
                        wp.Load(ds);
                    }
                }
            }


            ViewBag.categories = ct;

            ViewBag.whepons = wp;

            if (Request.IsAuthenticated)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }

        }
        public ActionResult Galery()
        {
            return View();
        }

    }
}

fabdefensAdmin/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace ask.Controllers
{
    public class LoginController : Controller
    {
        private const string User = "admin";
        private const string Pass = "admin";
        //
        // GET: /Login/

        public ActionResult Index()
        {
            return View();

        }

        [HttpPost]
        public ActionResult Login(String username, String password)
        {

            if (username == User && password == Pass)
            {
                FormsAuthentication.SetAuthCookie(username, true);
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Index", "Login");
        }
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

    }
}

fabdefensAdmin/Controllers/WheponsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ask.Controllers
{
    public class WheponsController : Controller
    {
        //
        // GET: /Whepons/

        public ActionResult Index()
        {
            return View();
        }

    }
}

fabdefensAdmin/Views/About/Index.cshtml
@{
    ViewBag.Title = "Контакты";
}

    <div class="row s-mb_18">

        <div class="col-md-12 col-lg-12 col-sm-12  col-xs-12">
            <div class="portlet">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-home"></i> Контактная информация
                    </div>
                    <div class="tools">
                        <a href="" class="collapse" title="Скрыть/Показать"></a>
                        <a href="" class="fullscreen" title="расширить"></a>
                        <a href="" class="remove" title="Убрать">
                        </a>
                    </div>
                </div>
                <div class="portlet-body form">

                    <div class="form-body">
                        <div class="form-group">
                            <label>Адрес, итд</label>
                            <textarea data-bind="wysiwyg:address, wysiwygConfig: {
                                            language: 'ru',plugins: [
                                                'advlist autolink lists link image charmap print preview anchor',
                                                'searchreplace visualblocks code fullscreen',
                                                'insertdatetime media table contextmenu paste'
                                            ],toolbar: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image'}" name="address" class="js-wysi form-control s-h_min_200 s-mb_9"></textarea>
                        </div>
                    </div>
                    <div class="form-actions">
                        <button data-bind="click:save" class="btn green">
                            <i class="fa fa-save"></i>&nbsp;Сохранить
                        </button>
                    </div>

                </div>
            </div>
        </div>
    </div>


<!-- editing -->
@section scripts{
    <script type="text/javascript" src="~/Content/js/knockout.js"></script>
    <script type="text/javascript" src="~/Content/js/knockout.mapping-latest.js"></script>
    <script type="text/javascript" src="~/Content/js/utils.js"></script>
    <script type="text/javascript" src="~/Content/js/tmce/tinymce.min.js"> </script>
    <script type="text/javascript" src="~/Content/js/tmce/jquery.tinymce.min.js"> </script>
    <script type="text/javascript" src="~/Content/js/wysiwyg.js"> </script>
    <script type="text/javascript" src="~/Content/js/models/aboutModel.js"></script>
    <script type="text/javascript">
        EC.getData("about");
        //tinymce.init({ selector: '.js-wysi', theme: "modern", language: "ru" });
    </script>
}

fabdefensAdmin/Views/Blog/Index.cshtml
@{
    ViewBag.Title = "Новости";
}

<div class="row s-mb_18">

    <div class="col-md-6">
        <div class="portlet">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-plus"></i> Новая запись
                </div>
                <div class="tools">
                    <a href="" class="collapse" title="Скрыть/Показать"></a>
                    <a href="" class="fullscreen" title="расширить"></a>
                    <a href="" class="remove" title="Убрать">
                    </a>
                </div>
            </div>
            <div class="portlet-body form">
                <form method="post" enctype="multipart/form-data" accept-charset="utf-8" action="/newBlog.php">
                    <div class="form-body">
                        <div class="form-group">
                            <label>Название</label>
                            <div class="input-icon s-mb_9">
                                <i class="fa fa-info-circle"></i>
                                <input name="name" type="text" class="form-control" placeholder="Название" />
                            </div>
                            <label>Описание краткое</label>
                            <textarea name="description" class="form-control s-mb_9"></textarea>
                            <div class="row s-mb_9">
                                <div class="col-md-6">
                                    <label>Дата</label>
                                    <input name="date" type="text" class="form-control s-mb_9" />
                                </div>
                                <div class="col-md-6">
                                    <label>Фото</label>
                                    <input name="image" type="file" class="form-control s-mb_18" />
                                </div>
                            </div>
                            <label>Описание полное</label>
                            <textarea name="description_full" class="js-wysi form-control s-h_min_200 s-mb_9"></textarea>
                        </div>
                    </div>
                    <div class="form-actions">
                        <button data-bind="" type="submit" class="btn green">
                            <i class="fa fa-save"></i>&nbsp;Сохранить
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div data-bind="if:items().length" class="col-md-6">
        <div class="portlet">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-pencil"></i> Редактирование записи
                </div>
                <div class="tools">
                    <a href="" class="collapse" title="Скрыть/Показать"></a>
                    <a href="" class="fullscreen" title="расширить"></a>
                    <a href="" class="remove" title="Убрать">
                    </a>
                </div>
            </div>
            <div class="portlet-body form">
                <form method="post" enctype="multipart/form-data" accept-charset="utf-8" action="/editBlog.php">
                    <div class="form-body">
                        <div class="form-group">
                            <div class="row s-mb_9">
                                <div class="col-lg-12 col-md-12 col-sm-12">
                                    <label><i class="fa fa-home s-mr_5"></i>Выберите запись</label>
                                    <select data-bind="options: items, optionsText: 'name', value: selectedItem, event:{change:updateWysiwygObservable}" class="form-control"></select>
                                </div>
                            </div>
                            <label>Название</label>
                            <div class="input-icon s-mb_9">
                                <i class="fa fa-info-circle"></i>
                                <input data-bind="value:selectedItem().name, valueUpdate:'input'" name="edit-name" type="text" class="form-control" placeholder="Название" />
                                <input data-bind="value:selectedItem().id" name="edit-id" type="hidden" />
                            </div>
                            <label>Описание краткое</label>
                            <textarea data-bind="value:selectedItem().description" name="edit-description" class="form-control s-mb_9"></textarea>
                            <div class="row s-mb_9">
                                <div class="col-md-6">
                                    <label>Дата</label>
                                    <input data-bind="value:selectedItem().date" name="edit-date" type="text" class="form-control s-mb_9" />
                                </div>
                                <div class="col-md-6">
                                    <label>Фото</label>
                                    <input name="edit-image" type="file" class="form-control s-mb_18" />
                                </div>
                            </div>
                            <label>Описание полное</label>
                            <textarea data-bind="wysiwyg:wysiwygObservable" name="edit-description_full" class="form-control s-h_min_200 s-mb_9"></textarea>

                        </div>
                    </div>
                    <div class="form-actions">
                        <button type="submit" class="btn green">
                            <i class="fa fa-save"></i>&nbsp;Сохранить
                        </button>
                        <a href="javascript:void(0);" data-bind="click:removeItem" class="btn blue">
                            <i class="fa fa-times"></i>&nbsp;Удалить
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>



<!-- editing -->
@section scripts{
    <script type="text/javascript" src="~/Content/js/knockout.js"></script>
    <script type="text/javascript" src="~/Content/js/utils.js"></script>
    <script type="text/javascript" src="~/Content/js/tmce/tinymce.min.js"> </script>
    <script type="text/javascript" src="~/Content/js/tmce/jquery.tinymce.min.js"> </script>
    <script type="text/javascript" src="~/Content/js/wysiwyg.js"> </script>
    <script type="text/javascript" src="~/Content/js/models/editModel.js"></script>
    <script type="text/javascript">
        EC.getData("blog", "all");
        tinymce.init({ selector: '.js-wysi',theme: "modern", language: "ru" });
    </script>
}

fabdefensAdmin/Views/Category/Index.cshtml
@{
    ViewBag.Title = "Категории";
}

<div class="row s-mb_18">
    <div class="col-md-6">
        <div class="portlet">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-pencil"></i> Добавление категории
                </div>
                <div class="tools">
                    <a href="" class="collapse" title="Скрыть/Показать"></a>
                    <a href="" class="fullscreen" title="расширить"></a>
                    <a href="" class="remove" title="Убрать">
                    </a>
                </div>
            </div>
            <div class="portlet-body form">
                <form method="post" enctype="multipart/form-data" accept-charset="utf-8" action="/newCategory.php">
                    <div class="form-body">
                        <div class="form-group">
                            <div class="row s-mb_9">
                                <div class="col-lg-12 col-md-12 col-sm-12">
                                    <label><i class="fa fa-home s-mr_5"></i>Название категории</label>
                                    <input name="name" class="form-control" type="text" />
                                </div>
                            </div>
                            <div class="row s-mb_9">
                                <div class="col-md-12">
                                    <label>Фото</label>
                                    <input name="image" type="file" class="form-control s-mb_18" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-actions">
                        <button type="submit" class="btn green">
                            <i class="fa fa-save"></i>&nbsp;Сохранить
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="portlet">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-pencil"></i> Редактирование категории
                </div>
                <div class="tools">
                    <a href="" class="collapse" title="Скрыть/Показать"></a>
                    <a href="" class="fullscreen" title="расширить"></a>
                    <a href="" class="remove" title="Убрать">
                    </a>
                </div>
            </div>
            <div class="portlet-body form">
                <form method="post" enctype="multipart/form-data" accept-charset="utf-8" action="/editCategory.php">
                    <div class="form-body">
                        <div class="form-group">
                            <div class="row s-mb_9">
                                <div class="col-lg-12 col-md-12 col-sm-12">
                                    <label><i class="fa fa-home s-mr_5"></i>Выберите категорию</label>
                                    <select data-bind="options: items, optionsText: 'name', value: selectedItem" class="form-control"></select>
                                    <input data-bind="value:selectedItem().id" name="edit-id" type="hidden" />
                                </div>
                            </div>
                            <div class="row s-mb_9">
                                <div class="col-lg-12 col-md-12 col-sm-12">
                                    <label>Название категории</label>
                                    <input data-bind="value:selectedItem().name" class="form-control" name="edit-name" type="text" />
                                </div>
                            </div>
                            <div class="row s-mb_9">
                                <div class="col-md-12">
                                    <label>Фото</label>
                                    <input name="edit-image" type="file" class="form-control s-mb_18" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-actions">
                        <button type="submit" class="btn green">
                            <i class="fa fa-save"></i>&nbsp;Сохранить
                        </button>
                        <a href="javascript:void(0);" data-bind="click:removeItem" class="btn blue">
                            <i class="fa fa-times"></i>&nbsp;Удалить
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>



<!-- editing -->
@section scripts{
    <script type="text/javascript" src="~/Content/js/knockout.js"></script>
    <script type="text/javascript" src="~/Content/js/utils.js"></script>
    <script type="text/javascript" src="~/Content/js/tmce/tinymce.min.js"> </script>
    <script type="text/javascript" src="~/Content/js/tmce/jquery.tinymce.min.js"> </script>
    <script type="text/javascript" src="~/Content/js/wysiwyg.js"> </script>
    <script type="text/javascript" src="~/Content/js/models/editModel.js"></script>
    <script type="text/javascript">
        EC.getData("categories", "all");
    </script>
}

fabdefensAdmin/Views/Home/Galery.cshtml
@{
    ViewBag.Title = "Загрузка дополнительных фоторгафий на страницу товара";
}
<link href="~/Content/css/uploadfile.css" rel="stylesheet">


<div class="row">
    <div class="col-md-12 col-lg-12 col-sm-12">
        <div id="multipleupload">Загрузка</div>
    </div>
</div>

@section scripts{
    <script type="text/javascript" src="~/Content/js/utils.js"></script>
    <script src="~/Content/js/jquery.uploadfile.min.js"></script>
    <script type="text/javascript">
        $("#multipleupload").uploadFile({
            url: "/upload.php",
            multiple: true,
            fileName: "myfile",
            formData: {
                directory:  document.location.hostname === "localhost"
                ? "I:/projects/fabdefense/fabdefense/fabdefense/Content/images/products/medium/" + document.location.search.substr(1) + "/"
                : "../Content/images/products/medium/" + document.location.search.substr(1) + "/"
            }
        });
    </script>
}

fabdefensAdmin/Views/Login/Index.cshtml
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}

<!-- BEGIN LOGO -->
<div class="logo">
    <a class="main-logo s-icon" href="/"></a>
</div>
<!-- END LOGO -->
<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
<div class="menu-toggler sidebar-toggler">
</div>
<!-- END SIDEBAR TOGGLER BUTTON -->
<!-- BEGIN LOGIN -->
<div class="content">
    <!-- BEGIN LOGIN FORM -->
    <form class="login-form" action="@Url.Action("Login")" method="post">
        <h3 class="form-title">Авторизация</h3>
        <div class="form-group">
            <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
            <label class="control-label visible-ie8 visible-ie9">Имя пользователя</label>
            <div class="input-icon">
                <i class="fa fa-user"></i>
                <input class="form-control placeholder-no-fix" type="text" autocomplete="off" placeholder="Имя пользователя" name="username" />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label visible-ie8 visible-ie9">Пароль</label>
            <div class="input-icon">
                <i class="fa fa-lock"></i>
                <input class="form-control placeholder-no-fix" type="password" autocomplete="off" placeholder="Пароль" name="password" />
            </div>
        </div>
        <div class="form-actions">
          
            <button type="submit" class="btn blue pull-right">
                Вход <i class="fa fa-arrow-circle-o-right"></i>
            </button>
        </div>
       
       
    </form>
    <!-- END LOGIN FORM -->
    <!-- BEGIN FORGOT PASSWORD FORM -->
    <form class="forget-form" action="index.html" method="post">
        <h3>Забыли пароль ?</h3>
        <p>
            Укажите адрес почты который Вы указывали при регистрации.
        </p>
        <div class="form-group">
            <div class="input-icon">
                <i class="fa fa-envelope"></i>
                <input class="form-control placeholder-no-fix" type="text" autocomplete="off" placeholder="Email" name="email" />
            </div>
        </div>
        <div class="form-actions">
            <button type="button" id="back-btn" class="btn">
                <i class="fa fa-arrow-circle-o-left"></i> Назад
            </button>
            <button type="submit" class="btn blue pull-right">
                Отправить <i class="fa fa-arrow-circle-o-right"></i>
            </button>
        </div>
    </form>
    <!-- END FORGOT PASSWORD FORM -->
    <!-- BEGIN REGISTRATION FORM -->
    <form class="register-form" action="index.html" method="post">
        <h3>Регистрация</h3>
        <p>
            Укажите персональную информацию:
        </p>
        <div class="form-group">
            <label class="control-label visible-ie8 visible-ie9">ФИО</label>
            <div class="input-icon">
                <i class="fa fa-font"></i>
                <input class="form-control placeholder-no-fix" type="text" placeholder="ФИО" name="fullname" />
            </div>
        </div>
        <div class="form-group">
            <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
            <label class="control-label visible-ie8 visible-ie9">Email</label>
            <div class="input-icon">
                <i class="fa fa-envelope"></i>
                <input class="form-control placeholder-no-fix" type="text" placeholder="Email" name="email" />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label visible-ie8 visible-ie9">Телефон</label>
            <div class="input-icon">
                <i class="fa fa-phone"></i>
                <input class="form-control placeholder-no-fix" type="text" placeholder="Телефон" name="address" />
            </div>
        </div>
        <p>
            Укажите данные для входа:
        </p>
        <div class="form-group">
            <label class="control-label visible-ie8 visible-ie9">Имя пользователя</label>
            <div class="input-icon">
                <i class="fa fa-user"></i>
                <input class="form-control placeholder-no-fix" type="text" autocomplete="off" placeholder="Имя пользователя" name="username" />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label visible-ie8 visible-ie9">Пароль</label>
            <div class="input-icon">
                <i class="fa fa-lock"></i>
                <input class="form-control placeholder-no-fix" type="password" autocomplete="off" id="register_password" placeholder="Пароль" name="password" />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label visible-ie8 visible-ie9">Повторите ввод пароля</label>
            <div class="controls">
                <div class="input-icon">
                    <i class="fa fa-check"></i>
                    <input class="form-control placeholder-no-fix" type="password" autocomplete="off" placeholder="Повторите ввод пароля" name="rpassword" />
                </div>
            </div>
        </div>
        <div class="form-group">
            <label>
                <input type="checkbox" name="tnc" /> Я согласен с <a href="#">
                    правилами пользования
                </a>
            </label>
            <div id="register_tnc_error">
            </div>
        </div>
        <div class="form-actions">
            <button id="register-back-btn" type="button" class="btn">
                <i class="fa fa-arrow-circle-o-left"></i> Назад
            </button>
            <button type="submit" id="register-submit-btn" class="btn blue pull-right">
                Завершить <i class="fa fa-arrow-circle-o-right"></i>
            </button>
        </div>
    </form>
    <!-- END REGISTRATION FORM -->
</div>
<!-- END LOGIN -->
<!-- BEGIN COPYRIGHT -->
<div class="copyright">
    @DateTime.Now.Year &copy; fab-defense russia
</div>
<!-- END COPYRIGHT -->

fabdefensAdmin/Views/Shared/PartialCountries.cshtml
<option value="Австралия">Австралия</option>
<option value="Великобритания">Великобритания</option>
<option value="Германия">Германия</option>
<option value="Голландия">Голландия</option>
<option value="Ирландия">Ирландия</option>
<option value="Испания">Испания</option>
<option value="Италия">Италия</option>
<option value="Канада">Канада</option>
<option value="Кипр">Кипр</option>
<option value="Китай">Китай</option>
<option value="Коста-Рика">Коста-Рика</option>
<option value="Малайзия">Малайзия</option>
<option value="Мальта">Мальта</option>
<option value="Россия">Россия</option>
<option value="Сингапур">Сингапур</option>
<option value="США">США</option>
<option value="Франция">Франция</option>
<option value="Чехия">Чехия</option>
<option value="Швейцария">Швейцария</option>
<option value="ЮАР">ЮАР</option>
<option value="Южная Корея">Южная Корея</option>
<option value="Япония">Япония</option>

fabdefensAdmin/Views/Shared/PartialCurrencyTypes.cshtml
<option value="643">РУБ</option>
<option value="840">USD</option>
<option value="978">EUR</option>
<option value="826">GBP</option>
<option value="124">CAD</option>
<option value="036">AUD</option>
<option value="756">CHF</option>

fabdefensAdmin/Views/Shared/PartialLangs.cshtml
<option value="Английский">Английский</option>
<option value="Испанский">Испанский</option>
<option value="Итальянский">Итальянский</option>
<option value="Китайский">Китайский</option>
<option value="Корейский">Корейский</option>
<option value="Немецкий">Немецкий</option>
<option value="Французский">Французский</option>
<option value="Японский">Японский</option>

fabdefensAdmin/Views/Shared/PartialMenu.cshtml
<li class="start active open">
    <a href="javascript:;">
        <i class="icon-home"></i>
        <span class="title">Контент</span>
        <span class="selected"></span>
        <span class="arrow open"></span>
    </a>
    <ul class="sub-menu">
        <li class="open">
            <a href="javascript:;">
                <i class="icon-login"></i>
                <span class="title">Товары</span>
                <span class="arrow open"></span>
            </a>
            <ul class="sub-menu" style="display: block;">
                <li>
                    <a href="@Url.Action("index", "Home")">
                        <i class="icon-pencil"></i>
                        Редактировать
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="@Url.Action("Index", "blog")">
                <i class="icon-calculator"></i>
                <span class="title">Новости</span>
            </a>
        </li>
        <li>
            <a href="@Url.Action("Index", "about")">
                <i class="icon-bar-chart"></i>
                <span class="title">Контакты</span>
            </a>
        </li>
        <li>
            <a href="@Url.Action("Index", "Category")">
                <i class="icon-bar-chart"></i>
                <span class="title">Категории</span>
            </a>
        </li>
        <li>
            <a href="@Url.Action("Index", "Whepons")">
                <i class="icon-bar-chart"></i>
                <span class="title">Орижие</span>
            </a>
        </li>
    </ul>
</li>

fabdefensAdmin/Views/Shared/PartialschoolTypes.cshtml
<option value="individual">Языковые школы</option>
<option value="higher">Высшее образование</option>
<option value="secondary">Среднее образование</option>

fabdefensAdmin/Views/Сooperation/Index.cshtml
@{
    ViewBag.Title = "Сотрудничество";
}